 build:
   image: docker:stable
   services:
     - docker:dind
   variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/nifaio/league-bot
     - docker build -t registry.gitlab.com/nifaio/league-bot:latest .
     - docker push registry.gitlab.com/nifaio/league-bot:latest
