image: docker:latest

services:
    - docker:dind

stages:
    - build
#    - test
    - release
    - deploy

variables:
    CONTAINER_IMAGE: registry.gitlab.com/nifaio/league-bot
    CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME

build:
  stage: build
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release_stg:
  stage: release
  tags:
    - docker
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:staging
    - docker push $CONTAINER_IMAGE:staging

deploy_stg:
  stage: deploy
  tags:
    - docker
  only:
    - master
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_IMAGE:staging
    - docker tag $CONTAINER_IMAGE:staging registry.heroku.com/league-discord-bot-staging/web
    - docker push registry.heroku.com/league-discord-bot-staging/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app league-discord-bot-staging
