 build:
   image: docker:stable
   services:
     - docker:dind
   variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/nifaio/league-bot
     - docker build -t registry.gitlab.com/nifaio/league-bot:staging .
     - docker push registry.gitlab.com/nifaio/league-bot:staging

deploy:
  stage: deploy
  services:
  - docker:dind
  script:
    - docker login --email=_ --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker tag registry.gitlab.com/nifaio/league-bot:staging registry.heroku.com/league-discord-bot-staging/web
    - docker push registry.heroku.com/league-discord-bot-staging/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app league-discord-bot-staging
